MSG_TYPE_REGISTER_REQUEST = 1
MSG_TYPE_REGISTER_RESPONSE = 2
MSG_TYPE_LOG_MESSAGE = 3
MSG_TYPE_LOG_BATCH = 4
MSG_TYPE_ACKNOWLEDGEMENT = 5
MSG_TYPE_OPTION_NEGOTIATE_REQ = 6
MSG_TYPE_HEARTBEAT_REQUEST = 7
MSG_TYPE_HEARTBEAT_RESPONSE = 8
MSG_TYPE_ERROR_RESPONSE = 9

STATUS_SUCCESS = 0
STATUS_ERROR = 1

DEFAULT_API_KEY = "admin:pass123"
PROTOCOL_VERSION = 1
